/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.7/samples
 */

plugins {
    java
}

repositories {
    mavenCentral()
}

dependencies {
    // twelvemonkeys for jpeg file support
    implementation("com.twelvemonkeys.imageio:imageio-jpeg:3.10.1")
}


